data:
    dataset: circa        
    root: /home/SPeillet/Partage/store-dai/tmp/speillet/                 # Data root directory
    hdf5_file: debug_circa.hdf5
    preprocessed: false
    split: iid
    channels: all-mask
    include_S1: true
    max_seq_length: 
    
misc:
    run_mode: test
