data:
    dataset: circa
    hdf5_file: /mnt/DATA_10T/data_rpg/circa/hdf5/CIRCA_CR_merged.hdf5
    load_transforms: ./data/CIRCA_patches_datasets_with_transforms.json
    channels: all
    use_sar: mix_closest
    subset: False
    max_seq_length: 5
    return_windows: true
    filter_settings:
        type: cloud-free
        min_length: 5
        return_valid_obs_only: true

test_data:
    checkpoint: /home/SPeillet/data_rpg/outputs/U-TILISE/results/all_bands_sar_closest_mix_da/checkpoints/Model_best.pth
    test_config: /home/SPeillet/data_rpg/outputs/U-TILISE/results/all_bands_sar_closest_mix_da/config.yaml
    data_optique: /mnt/stores/store_dai/projets/pac/3str/EXP_2/Data_Raster/optique_dataset
    data_radar: /mnt/stores/store_dai/projets/pac/3str/EXP_2/Data_Raster/radar_dataset_v4
    data_masks: /mnt/stores/store_dai/projets/pac/3str/EXP_2/Data_Raster/test_v3/aleatoire
    mask_type: fully_masked
    test_tiles: "./data/MGRSC_test.json"
    mode: null
    split: test

mask:
    mask_type: random_fully_masked
    ratio_masked_frames: 0.5
    ratio_fully_masked_frames: 0.0
    fixed_masking_ratio: false
    non_masked_frames: [0]
    intersect_real_cloud_masks: false
    dilate_cloud_masks: false
    fill_type: fill_value
    fill_value: 1
    p_filter: 0.1

utilise:
  encoder_widths:
  - 64
  - 64
  - 64
  - 128
  decoder_widths:
  - 64
  - 64
  - 64
  - 128
  upconv_type: transpose
  encoder_norm: null
  decoder_norm: null
  skip_norm: null
  activation: relu
  str_conv_k: 4
  str_conv_s: 2
  str_conv_p: 1
  str_conv_k_up: 2
  str_conv_p_up: 0
  skip_attention: false
  n_temporal_encoding_layers: 1
  agg_mode: att_group
  n_head: 4
  d_k: 4
  bias_qk: false
  attn_dropout: 0.1
  dropout: 0.1
  n_groups: 4
  ltae_norm: group
  ltae_activation: gelu
  norm_first: true
  output_activation: sigmoid

training_settings:
    batch_size: 1
    num_epochs: 1
    accum_iter: 1
    gradient_clip_norm: 0
    gradient_clip_value: 0
    resume: false
    pretrained_path: ''

method:
    model_type: utilise
    pad_value: 0

metrics:
    masked_metrics: true
    mae: true
    mse: true
    rmse: true
    ssim: true
    psnr: true
    sam: true

misc:
    num_workers: 8
    pin_memory: false
    run_mode: test

output:
    save_dir: /mnt/DATA_10T/data_rpg/outputs/U-TILISE/inference/tiles_aleatoire
