data:
  dataset: circa
  hdf5_file: ${oc.env:HDF5_FILE}
  load_transforms: ${oc.env:LOAD_TRANSFORMS,./metadata/patches_with_transforms.json}
  channels: all
  use_sar: asc+desc
  subset: false
  max_seq_length: 14
  blend_mode: center_only
  center_only_n_keep: 2
  filter_settings:
    type: cloud-free
    min_length: 5
    return_valid_obs_only: true
test_data:
  checkpoint: /mnt/common/hdd/home/SPeillet/outputs/U-TILISE/v4_asc_desc_random_clouds_combined/2026-03-29_16-10/checkpoints/Model_best.pth
  test_config: /mnt/common/hdd/home/SPeillet/outputs/U-TILISE/v4_asc_desc_random_clouds_combined/2026-03-29_16-10/config.yaml
  hdf5_file: ${oc.env:HDF5_FILE}
  mode: null
  split: test
mask:
  mask_type: consecutive_fully_masked
utilise:
  encoder_widths:
  - 64
  - 96
  - 128
  - 192
  - 256
  decoder_widths:
  - 96
  - 128
  - 192
  - 192
  - 256
  n_head: 8
  d_k: 4
  n_groups: 8
training_settings:
  batch_size: 1
  num_epochs: 1
misc:
  num_workers: 12
  pin_memory: true
  run_mode: test
output:
  save_dir: ${oc.env:OUTPUT_DIR}/metrics/v4_asc_desc_random_clouds_combined_center_only/consecutive_fully_masked
