data:
    dataset: circa         # Name of the dataset, ['earthnet2021', 'sen12mscrts']
    hdf5_file: /var/data/datasets/CIRCA_CR_merged.hdf5
    max_seq_length: 12
    channels: all
    use_sar: asc+desc # asc / desc / mix_closest / asc+desc
    image_size: [256, 256]
    subset: false
    filter_settings:
        type: cloud-free
        min_length: 5
        return_valid_obs_only: true
        # max_t_sampling: 28

mask:
    mask_type: random_clouds               # Mask the input time series with randomly sampled cloud masks or the actual cloud masks. ['random_clouds', 'real_clouds']
    ratio_masked_frames: 0.5               # Ratio of partially/fully masked images per image time series (upper bound).
    ratio_fully_masked_frames: 0.0         # Ratio of fully masked images per image time series (upper bound).
    fixed_masking_ratio: false             # True to vary the masking ratio across different image time series, False otherwise.
    non_masked_frames: [0]                 # list of int, time steps to be excluded from masking. E.g., [0] never masks the first frame in a sequence.
    intersect_real_cloud_masks: true      # True to intersect randomly sampled cloud masks with the actual cloud masks, False otherwise.
    dilate_cloud_masks: false              # True to dilate the cloud masks before masking, False otherwise.
    fill_type: fill_value                  # Strategy for initializing masked pixels. ['fill_value', 'white_noise', 'mean']
    fill_value: 1                          # Pixel value of masked pixels. Used if fill_type == 'fill_value'.
    p_filter: 0.1

method:
    model_type: utilise
    pad_value: 0

utilise:                                   
    encoder_widths: [64,64,64,64,128]
    decoder_widths: [64,64,64,64,128]

optimizer:
    name: Adam
    learning_rate: 2.e-04
    weight_decay: 1.0e-05

scheduler:
    name: CosineAnnealingWarmRestarts
    enabled: true
    T_0: 30
    T_mult: 1
    eta_min: !!float 1e-6

training_settings:
    early_stopping_patience: 30
    batch_size: 6                          # Batch size.
    num_epochs: 120                       # Number of training epochs.
    accum_iter: 1                          # Accumulate gradients for 'accum_iter` iterations.
    gradient_clip_norm: 0                  # If > 0, clips gradient norm to that value.
    gradient_clip_value: 0                 # If > 0, clips gradient at specified value.
    resume: false                          # True to resume training, False otherwise.
    pretrained_path: ''                    # Path to the pretrained model weights.

misc:
    logstep_train: 100                     # Training log interval in number of iterations.
    checkpoint_every_n_epochs: 5           # Save checkpoint after every `checkpoint_every_n_epochs` training epochs.
    log_gradients: false                   # True to log gradients and model parameters using Weights & Biases.
    val_every_n_epochs: 1                  # Validation interval in epochs.
    plot_every_n_epochs: 15                # Plot interval in epochs.
    plot_val_sample: []                    # List of int, indices of the validation samples to be visualized during training using Weights & Biases.
    num_workers: 12                         # Number of dataloader worker processes.
    random_seed: 42                         # Random seed.
    pin_memory: true                      # Pin memory (dataloader settings).
    run_mode: train                        # Run mode. ['train', 'val', 'test']

